export const ItemTypes = {
    ADD_COMPONENT: 'ADD_COMPONENT',
    EXISTING_COMPONENT: 'EXISTING_COMPONENT',

    ADD_WIDGET: 'ADD_WIDGET',
    REMOVE_WIDGET: 'REMOVE_WIDGET',

    ADD_SHADOWN_WIDGET: 'ADD_SHADOW_WIDGET',
    REMOVE_SHADOW_WIDGET: 'REMOVE_SHADOW_WIDGET',

    CONTAINERS_PER_PANEL: 3,
    WIDGET_HEIGHT: 350
};
